### ISSUE TITLE
Error on building

### ISSUE THREAD

**Issue by BBassi** [yeebc/jupyterlab-neon-theme#11]
Jupyterlab  Version 2.2.8

Run: !jupyter labextension install @yeebc/jupyterlab_neon_theme

"@yeebc/jupyterlab_neon_theme changed from file:../extensions/yeebc-jupyterlab_neon_theme-2.0.0.tgz to file:../extensions/yeebc-jupyterlab_neon_theme-2.0.1.tgz"

![Screenshot 2020-10-26 at 09 32 26](https://user-images.githubusercontent.com/25634627/97156193-4536e900-176e-11eb-8e11-0b348febf73e.png)

![Screenshot 2020-10-26 at 09 34 24](https://user-images.githubusercontent.com/25634627/97156310-744d5a80-176e-11eb-98cf-420cf22c618c.png)

**Comment by yeebc** [comment]
Hi, did you have a development installation, and at the same time try to install from the npm package?

**Comment by BBassi** [comment]
No I just tried to install directly into Jupyterlab: Command in notebook: '!jupyter labextension install @yeebc/jupyterlab_neon_theme'

**Comment by yeebc** [comment]
Well...sorry currently I have no idea for why. I will figure out it later. For now I would suggest you clone this repo in your computer and try the development installation.

**Comment by yeebc** [comment]
Please try the lastest version , and let me know if it still doesn't work for you.
