### ISSUE TITLE
Syntax coloring for Python scripts does not comply with the Neon-themed notebooks

### ISSUE THREAD

**Issue by shahrokh-bahtooei** [yeebc/jupyterlab-neon-theme#13]
I like Neon Theme for notebooks, and my eyes have gotten used to it. Refactoring a notebook and moving functions to Python scripts, I see a different syntax coloring in scripts, though. 

<img width="501" alt="notebook" src="https://user-images.githubusercontent.com/42028078/102706950-acbf6f80-42ab-11eb-88ad-079fd686b748.png">

<img width="484" alt="script" src="https://user-images.githubusercontent.com/42028078/102706957-bf39a900-42ab-11eb-9ddf-d28ea2340e17.png">

This is important for people who often use Python scripts along with notebooks.

**Comment by yeebc** [comment]
That's weird. I guess you may need to check your jlab setting where you may set to use another color scheme for the scripts.

**Comment by shahrokh-bahtooei** [comment]
> That's weird. I guess you may need to check your jlab setting where you may set to use another color scheme for the scripts.

Wow . . . Thank you very much!
I found that in `JupyterLab > Menu > Settings > Text Editor Theme`, `jupyter` should be selected, which for me was set to `base16-dark` before installing Neon Theme.
