### ISSUE TITLE
Jupyter lab saying this extension does not support >=3.0

### ISSUE THREAD

**Issue by 614nK** [yeebc/jupyterlab-neon-theme#17]
Tried running the install and got the following response:
<img width="873" alt="Screen Shot 2021-02-28 at 4 09 04 PM" src="https://user-images.githubusercontent.com/49792909/109438579-7b67cc00-79df-11eb-8c06-6ccd0a69f8d6.png">

Am I just doing something wrong? (New to jupyter lab)

**Comment by yeebc** [comment]
I have published the lastest version for the npm package. Please try agian and tell me if it works.

**Comment by mjspeck** [comment]
Worked! Awesome

**Comment by 614nK** [comment]
Yes!!! Thank you! Looks beautiful!! 👍 😊
