### ISSUE TITLE
Theme is applied to JupyterLab's UI even when it is not the selected theme

### ISSUE THREAD

**Issue by norweeg** [yeebc/jupyterlab-neon-theme#18]
I have a different theme selected at the moment, however jupyterlab_neon_theme is still styling UI elements

![image](https://user-images.githubusercontent.com/5969754/127366386-a4f34681-1699-4766-94f6-673562a49627.png)

![image](https://user-images.githubusercontent.com/5969754/127366541-4d118555-2fe0-43b4-a801-94124aa8b79e.png)
Python 3.9.6
Node v16.5.0

**Comment by yeebc** [comment]
Sorry for that. It happened when I used&nbsp;jupyter labextension develop --overwrite .&nbsp;


How did you install the neon theme, via&nbsp;jupyter labextension install&nbsp;or something else?


---Original---
From: "Brennen ***@***.***&gt;
Date: Thu, Jul 29, 2021 01:12 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [yeebc/jupyterlab-neon-theme] Theme is applied to JupyterLab's UI even when it is not the selected theme (#18)




 
I have a different theme selected at the moment, however jupyterlab_neon_theme is still styling UI elements
 

 

 Python 3.9.6
 Node v16.5.0

**Comment by norweeg** [comment]
I don't remember.  I installed it some time ago and did not uninstall it.  I recently updated my JupyterLab, so as a matter of habit, I also ran `jupyter labextension update --all` and `jupyter lab build` afterwards

**Comment by miwojc** [comment]
i have the same issue. installed with this command:
```
jupyter labextension install @yeebc/jupyterlab_neon_theme
```
JupyterLab version 3.1.7

Additionally JupyterLab Vim extension stopped working. I uninstalled the Neon theme and after that JupyterLab Vim is back. Uinstalled it with: 
```
jupyter labextension uninstall @yeebc/jupyterlab_neon_theme
```

**Comment by dd-ugm** [comment]
Same issue here. I installed via JupyterLab extension manager and `jupyter lab build`.

Edit: [Miami Nights](https://github.com/timkpaine/jupyterlab_miami_nights) fork has a similar issue.

**Comment by vidartf** [comment]
See the updated docs here: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#theme-plugins

> Theme CSS assets are specially bundled in an extension (see [Theme path](https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#themepath)) so they can be unloaded or loaded as the theme is activated. Since CSS files referenced by the style or styleModule keys are automatically bundled and loaded on the page, the theme files should not be referenced by these keys.

I think the fix is to remove the "style" key from package.json.
