### ISSUE TITLE
Last line of cell gets hidden

### ISSUE THREAD

**Issue by kirtan-desai** [yeebc/jupyterlab-neon-theme#4]
The lower part of last line of cell gets hidden for some reason. Kindly look into it. Attaching screenshot.
![Annotation 2020-03-12 162215](https://user-images.githubusercontent.com/53828181/76514450-e7bf8780-647d-11ea-9764-acea2570f79e.png)

**Comment by yeebc** [comment]
Hi, thanks for your feedback. I am not sure what's going on here as this issue didn't arise in my cells. Could you please provide more information? Does it happend in all cells or a specific cell? What kind of browser you are using? In the best case, you can offer a html file, which can be saved via browser, concerning  the webpage with this issue.

**Comment by kirtan-desai** [comment]
Hey it works fine now. I don't know why it was working like that earlier. Was freshly installed. Thanks.
Also, I absolutely the neon theme <3
