### ISSUE TITLE
More explicit guide for installation

### ISSUE THREAD

**Issue by Maxence-L** [yeebc/jupyterlab-neon-theme#5]
Hello, your theme is great !

I have a suggestion concerning the installation guide in the readme. Maybe you can mention that it is installable also from the "extensions" left pane bar in jupyterlab, which is very convenient.

Besides, the node.js/npm installation part is a little bit confusing, since installing node.js installs automatically npm (from what I've understand).

Maybe we could replace the installation code by :

`pip install nodejs`
`jupyter labextension install @yeebc/jupyterlab_neon_theme`

or with conda

`conda install -c conda-forge nodejs`
`jupyter labextension install @yeebc/jupyterlab_neon_theme`

And mention, with a screenshot, the fact that you can install it from left pane.

Kind regards, thanks again for the awesome theme ! 💯

**Comment by yeebc** [comment]
Sorry for my late reply since I was busy in assigments these days. Thanks for your advices and I will update it soon.

**Comment by yeebc** [comment]
Updated
