### ISSUE TITLE
Vim-Keybindings Cursor is always a Bar

### ISSUE THREAD

**Issue by RyannDaGreat** [yeebc/jupyterlab-neon-theme#9]
When using the vim-keybindings plugin, from @axlair/jupyterlab_vim, usually when you're in normal mode (while editing a cell), the cursor is supposed to be a box (like in a normal terminal) highlighting the character you're on. But when using this theme, it turns it into a bar, and I have no idea whether I'm in normal mode or in insert mode

**Comment by yeebc** [comment]
I am sorry it's my fault but fixed now. Thanks for your feedback : )
